version: '3.9'
services:
  api:
    build: .
    container_name: mega-market-api
    image: mega-market:latest
    environment:
      DB_URL: "market_app:backend_school_2022@db:5432/mega_market"
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mega-market-network
    command: >
      sh -c "cd market && alembic upgrade head && cd - &&
             uvicorn market.api.main:app --host 0.0.0.0 --port 80 --log-level info"
    restart: always
  db:
    image: postgres:13.7
    container_name: mega-market-db
    environment:
      POSTGRES_DB: "mega_market"
      POSTGRES_USER: "market_app"
      POSTGRES_PASSWORD: "backend_school_2022"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    command:
      - "postgres"
      - "-c"
      - "max_connections=30"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=64MB"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "max_prepared_transactions=30"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=5GB"
      - "-c"
      - "log_min_error_statement=INFO"
      - "-c"
      - "log_min_messages=FATAL"
      - "-c"
      - "log_statement=none"
      - "-c"
      - "log_destination=stderr"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U market_app -d mega_market"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 7s
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mega-market-network

networks:
  mega-market-network:
    driver: bridge
