"""Initialal migration

Revision ID: 8c7450a4068e
Revises: 
Create Date: 2022-06-25 07:00:03.214582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c7450a4068e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_price', sa.BigInteger(), nullable=True),
    sa.Column('offers_number', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.uuid'], name=op.f('fk_categories_parent_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_categories'))
    )
    op.create_index('category_parent_id_idx', 'categories', ['parent_id'], unique=False)
    op.create_table('categories_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_price', sa.BigInteger(), nullable=True),
    sa.Column('offers_number', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.uuid'], name=op.f('fk_categories_history_parent_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uuid'], ['categories.uuid'], name=op.f('fk_categories_history_uuid_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories_history'))
    )
    op.create_table('offers',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.uuid'], name=op.f('fk_offers_parent_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_offers'))
    )
    op.create_index('offer_parent_id_idx', 'offers', ['parent_id'], unique=False)
    op.create_table('shop_units',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.Enum('OFFER', 'CATEGORY', name='shopunittype'), nullable=False),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.uuid'], name=op.f('fk_shop_units_parent_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_shop_units'))
    )
    op.create_table('offers_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.uuid'], name=op.f('fk_offers_history_parent_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uuid'], ['offers.uuid'], name=op.f('fk_offers_history_uuid_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers_history')
    op.drop_table('shop_units')
    op.drop_index('offer_parent_id_idx', table_name='offers')
    op.drop_table('offers')
    op.drop_table('categories_history')
    op.drop_index('category_parent_id_idx', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
